import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'src/core/constants/firebase_env.dart';

/// Stubbed Firebase configuration used during development.
///
/// Replace the placeholder values with those generated by `flutterfire configure`
/// before running the application.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _ensureOptions('web', web, requiredKeys: const [
        'apiKey',
        'appId',
        'messagingSenderId',
        'projectId',
      ]);
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _ensureOptions('android', android, requiredKeys: const [
          'apiKey',
          'appId',
          'messagingSenderId',
          'projectId',
        ]);
      case TargetPlatform.iOS:
        return _ensureOptions('ios', ios, requiredKeys: const [
          'apiKey',
          'appId',
          'messagingSenderId',
          'projectId',
          'iosBundleId',
        ]);
      case TargetPlatform.macOS:
        return _ensureOptions('macos', macos, requiredKeys: const [
          'apiKey',
          'appId',
          'messagingSenderId',
          'projectId',
          'iosBundleId',
        ]);
      case TargetPlatform.windows:
        return _ensureOptions('windows', windows);
      case TargetPlatform.linux:
        return _ensureOptions('linux', linux);
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for platform $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FIREBASE_WEB_API_KEY,
    appId: FIREBASE_WEB_APP_ID,
    messagingSenderId: FIREBASE_WEB_MESSAGING_SENDER_ID,
    projectId: FIREBASE_WEB_PROJECT_ID,
    authDomain: FIREBASE_WEB_AUTH_DOMAIN,
    storageBucket: FIREBASE_WEB_STORAGE_BUCKET,
    measurementId: FIREBASE_WEB_MEASUREMENT_ID,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FIREBASE_ANDROID_API_KEY,
    appId: FIREBASE_ANDROID_APP_ID,
    messagingSenderId: FIREBASE_ANDROID_MESSAGING_SENDER_ID,
    projectId: FIREBASE_ANDROID_PROJECT_ID,
    storageBucket: FIREBASE_ANDROID_STORAGE_BUCKET,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FIREBASE_APPLE_API_KEY,
    appId: FIREBASE_APPLE_APP_ID,
    messagingSenderId: FIREBASE_APPLE_MESSAGING_SENDER_ID,
    projectId: FIREBASE_APPLE_PROJECT_ID,
    storageBucket: FIREBASE_APPLE_STORAGE_BUCKET,
    iosBundleId: FIREBASE_IOS_BUNDLE_ID,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FIREBASE_APPLE_API_KEY,
    appId: FIREBASE_APPLE_APP_ID,
    messagingSenderId: FIREBASE_APPLE_MESSAGING_SENDER_ID,
    projectId: FIREBASE_APPLE_PROJECT_ID,
    storageBucket: FIREBASE_APPLE_STORAGE_BUCKET,
    iosBundleId: FIREBASE_IOS_BUNDLE_ID,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: FIREBASE_WINDOWS_API_KEY,
    appId: FIREBASE_WINDOWS_APP_ID,
    messagingSenderId: FIREBASE_WINDOWS_MESSAGING_SENDER_ID,
    projectId: FIREBASE_WINDOWS_PROJECT_ID,
    storageBucket: FIREBASE_WINDOWS_STORAGE_BUCKET,
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: FIREBASE_LINUX_API_KEY,
    appId: FIREBASE_LINUX_APP_ID,
    messagingSenderId: FIREBASE_LINUX_MESSAGING_SENDER_ID,
    projectId: FIREBASE_LINUX_PROJECT_ID,
    storageBucket: FIREBASE_LINUX_STORAGE_BUCKET,
  );

  static FirebaseOptions _ensureOptions(
    String platform,
    FirebaseOptions options, {
    List<String> requiredKeys = const [],
  }) {
    final missing = <String>[];
    for (final key in requiredKeys) {
      switch (key) {
        case 'apiKey':
          if (options.apiKey.isEmpty) missing.add('apiKey');
          break;
        case 'appId':
          if (options.appId.isEmpty) missing.add('appId');
          break;
        case 'messagingSenderId':
          if (options.messagingSenderId.isEmpty) {
            missing.add('messagingSenderId');
          }
          break;
        case 'projectId':
          if (options.projectId.isEmpty) missing.add('projectId');
          break;
        case 'iosBundleId':
          if ((options.iosBundleId ?? '').isEmpty) missing.add('iosBundleId');
          break;
        case 'storageBucket':
          if ((options.storageBucket ?? '').isEmpty) {
            missing.add('storageBucket');
          }
          break;
      }
    }
    if (missing.isNotEmpty) {
      throw StateError(
        'Missing Firebase configuration for $platform: ${missing.join(', ')}. '
        'Provide values via --dart-define or .env (see .env.example).',
      );
    }
    return options;
  }
}
